In [72]:
import quandl
from datetime import datetime
import pandas as pd
import requests
import json

# url = 'https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty'
# r = requests.get(url)
# print(json.loads(r.content))
# "https://www.quandl.com/api/v3/datasets/WIKI/FB/metadata.json?api_key=YOURAPIKEY"

In [73]:
#quandl.ApiConfig.api_key = '-VWwJTwTXLhfXXjqqmkz'
quandl.ApiConfig.api_key = "V2vzspYSYL8eenGuq8uF"
# url = 'https://www.quandl.com/api/v3/databases/EOD/IBM/metadata.json?api_key=V2vzspYSYL8eenGuq8uF'
# r = requests.get(url)
# r

In [74]:
mydata2 = quandl.get("WIKI/IBM",collapse="monthly")
mydata2.head(10)

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
1962-01-31,530.50,542.00,530.50,542.00,38000.0,0.0,1.0,14.003769,14.307338,14.003769,14.307338,760000.0
1962-02-28,536.00,537.00,533.00,537.00,13360.0,0.0,1.0,14.148954,14.175351,14.069762,14.175351,267200.0
1962-03-31,537.00,537.00,530.25,532.75,21760.0,0.0,1.0,14.175351,14.175351,13.997170,14.063163,435200.0
1962-04-30,485.50,490.00,450.00,454.00,117200.0,0.0,1.0,12.815890,12.934678,11.878786,11.984375,2344000.0
1962-05-31,390.00,400.00,390.00,392.50,206400.0,0.0,1.0,10.294948,10.558921,10.294948,10.360941,4128000.0
1962-06-30,344.00,347.50,338.25,339.25,141200.0,0.0,1.0,9.080672,9.173063,8.928888,8.955285,2824000.0
1962-07-31,387.37,393.50,387.00,387.00,138560.0,0.0,1.0,10.225523,10.387338,10.215756,10.215756,2771200.0
1962-08-31,388.50,397.75,388.50,396.25,61360.0,0.0,1.0,10.255352,10.499527,10.255352,10.459931,1227200.0
1962-09-30,350.25,356.50,350.25,353.50,70800.0,0.0,1.0,9.245655,9.410638,9.245655,9.331446,1416000.0
1962-10-31,351.00,351.00,344.25,346.00,58800.0,0.0,1.0,9.265453,9.265453,9.087271,9.133467,1176000.0

In [76]:
IBMdata = mydata2[["Open","High","Low","Close","Volume","Split Ratio"]]
IBMdata

              Open      High      Low   Close     Volume  Split Ratio
Date
1962-01-31  530.50  542.0000  530.500  542.00    38000.0          1.0
1962-02-28  536.00  537.0000  533.000  537.00    13360.0          1.0
1962-03-31  537.00  537.0000  530.250  532.75    21760.0          1.0
1962-04-30  485.50  490.0000  450.000  454.00   117200.0          1.0
1962-05-31  390.00  400.0000  390.000  392.50   206400.0          1.0
1962-06-30  344.00  347.5000  338.250  339.25   141200.0          1.0
1962-07-31  387.37  393.5000  387.000  387.00   138560.0          1.0
1962-08-31  388.50  397.7500  388.500  396.25    61360.0          1.0
1962-09-30  350.25  356.5000  350.250  353.50    70800.0          1.0
1962-10-31  351.00  351.0000  344.250  346.00    58800.0          1.0
1962-11-30  401.00  401.7500  397.250  398.50    64960.0          1.0
1962-12-31  392.50  394.7500  389.500  390.00    52400.0          1.0
1963-01-31  419.50  424.0000  418.000  423.75    49760.0          1.0
1963-02-28  405.25  405.5000  399.000  399.75    56000.0          1.0
1963-03-31  420.75  422.2500  420.000  421.00    24000.0          1.0
1963-04-30  468.50  471.0000  462.000  463.75    43360.0          1.0
1963-05-31  472.00  478.5000  472.000  477.25    53360.0          1.0
1963-06-30  435.50  438.2500  435.500  436.25    32400.0          1.0
1963-07-31  443.00  448.0000  434.500  434.50    56960.0          1.0
1963-08-31  442.50  445.0000  439.500  444.75    33600.0          1.0
1963-09-30  448.50  452.5000  447.000  452.00    32000.0          1.0
1963-10-31  484.25  494.0000  484.000  494.00    35360.0          1.0
1963-11-30  478.00  486.7500  477.500  485.25    33760.0          1.0
1963-12-31  500.50  509.5000  500.500  507.00    86960.0          1.0
1964-01-31  531.00  542.0000  531.000  542.00    32000.0          1.0
1964-02-29  566.50  572.0000  563.000  569.00    32400.0          1.0
1964-03-31  589.50  594.5000  589.500  594.25    51760.0          1.0
1964-04-30  576.50  578.0000  570.250  570.25    18800.0          1.0
1964-05-31  477.00  480.0000  477.000  480.00    22160.0          1.0
1964-06-30  477.25  479.0000  477.000  477.00    14560.0          1.0
...            ...       ...      ...     ...        ...          ...
2015-10-31  140.44  141.3300  139.900  140.08  3983990.0          1.0
2015-11-30  138.61  139.9000  138.520  139.42  4542014.0          1.0
2015-12-31  139.07  139.1000  137.570  137.62  3462037.0          1.0
2016-01-31  123.28  124.7900  122.960  124.79  8248077.0          1.0
2016-02-29  132.00  133.3600  130.900  131.03  4427472.0          1.0
2016-03-31  149.79  153.1000  149.360  151.45  6780132.0          1.0
2016-04-30  146.49  147.3400  144.191  145.94  4225790.0          1.0
2016-05-31  152.56  153.8100  152.270  153.74  5836645.0          1.0
2016-06-30  148.86  151.9100  148.670  151.78  3967126.0          1.0
2016-07-31  161.36  161.6700  160.030  160.62  3547395.0          1.0
2016-08-31  159.66  159.6600  158.260  158.88  2323649.0          1.0
2016-09-30  158.90  159.8380  158.060  158.85  3596878.0          1.0
2016-10-31  152.76  154.3300  152.760  153.69  3553172.0          1.0
2016-11-30  163.35  163.8000  162.210  162.22  4397777.0          1.0
2016-12-31  166.44  166.7000  165.500  165.99  2952200.0          1.0
2017-01-31  175.05  175.5800  173.610  174.52  4134049.0          1.0
2017-02-28  179.38  180.6300  179.350  179.82  3273335.0          1.0
2017-03-31  173.98  174.9500  173.690  174.14  2913684.0          1.0
2017-04-30  160.50  160.5900  159.700  160.29  4029533.0          1.0
2017-05-31  152.03  152.8000  151.650  152.63  3496466.0          1.0
2017-06-30  154.28  154.5000  153.140  153.83  3501395.0          1.0
2017-07-31  144.38  144.9300  144.170  144.67  4333680.0          1.0
2017-08-31  143.02  143.6600  142.630  143.03  3614517.0          1.0
2017-09-30  145.45  145.6900  144.920  145.08  2635887.0          1.0
2017-10-31  154.33  154.9300  152.930  154.06  4224346.0          1.0
2017-11-30  153.65  154.4100  153.080  153.97  6254399.0          1.0
2017-12-31  154.17  154.7200  153.415  153.42  3310894.0          1.0
2018-01-31  163.75  164.9900  162.761  163.70  4025105.0          1.0
2018-02-28  157.50  158.1399  155.800  155.83  3761597.0          1.0
2018-03-31  153.95  154.8697  151.160  151.91  3810994.0          1.0

[675 rows x 6 columns]

In [77]:
IBMdata.reset_index(inplace = True)

IBMdata.head()

        Date   Open   High     Low   Close    Volume  Split Ratio
0 1962-01-31  530.5  542.0  530.50  542.00   38000.0          1.0
1 1962-02-28  536.0  537.0  533.00  537.00   13360.0          1.0
2 1962-03-31  537.0  537.0  530.25  532.75   21760.0          1.0
3 1962-04-30  485.5  490.0  450.00  454.00  117200.0          1.0
4 1962-05-31  390.0  400.0  390.00  392.50  206400.0          1.0

In [79]:
##mydata10 = quandl.get("EOD/AAPL",collapse="monthly")
mydata10 = quandl.get("WIKI/AAPL", collapse="monthly", start_date="1980-12-31", end_date="2019-04-30")
# mydata2 = quandl.get("EOD/IBM")
mydata10.head()
mydata10.count()
mydata10

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
1980-12-31,34.25,34.2500,34.13,34.13,159600.0,0.0,1.0,0.503571,0.503571,0.501807,0.501807,8937600.0
1981-01-31,28.50,28.5000,28.25,28.25,206200.0,0.0,1.0,0.419030,0.419030,0.415355,0.415355,11547200.0
1981-02-28,26.50,26.7500,26.50,26.50,65900.0,0.0,1.0,0.389625,0.393300,0.389625,0.389625,3690400.0
1981-03-31,24.75,24.7500,24.50,24.50,71400.0,0.0,1.0,0.363895,0.363895,0.360219,0.360219,3998400.0
1981-04-30,28.38,28.6200,28.38,28.38,56300.0,0.0,1.0,0.417266,0.420795,0.417266,0.417266,3152800.0
1981-05-31,33.13,33.2500,33.13,33.13,265100.0,0.0,1.0,0.487104,0.488869,0.487104,0.487104,14845600.0
1981-06-30,26.13,26.1300,26.00,26.00,160300.0,0.0,1.0,0.384185,0.384185,0.382273,0.382273,8976800.0
1981-07-31,25.00,25.1200,25.00,25.00,48900.0,0.0,1.0,0.367570,0.369335,0.367570,0.367570,2738400.0
1981-08-31,20.13,20.2500,20.13,20.13,182800.0,0.0,1.0,0.295968,0.297732,0.295968,0.295968,10236800.0
1981-09-30,15.25,15.3700,15.25,15.25,223200.0,0.0,1.0,0.224218,0.225982,0.224218,0.224218,12499200.0
1981-10-31,20.00,20.1300,20.00,20.00,235400.0,0.0,1.0,0.294056,0.295968,0.294056,0.294056,13182400.0
1981-11-30,18.75,18.7500,18.63,18.63,107000.0,0.0,1.0,0.275678,0.275678,0.273913,0.273913,5992000.0
1981-12-31,22.13,22.2500,22.13,22.13,244000.0,0.0,1.0,0.325373,0.327138,0.325373,0.325373,13664000.0
1982-01-31,20.38,20.5000,20.38,20.38,237300.0,0.0,1.0,0.299643,0.301408,0.299643,0.299643,13288800.0
1982-02-28,18.25,18.3700,18.25,18.25,77800.0,0.0,1.0,0.268326,0.270091,0.268326,0.268326,4356800.0
1982-03-31,16.88,17.0000,16.88,16.88,223900.0,0.0,1.0,0.248184,0.249948,0.248184,0.248184,12538400.0
1982-04-30,14.75,14.8700,14.75,14.75,1238400.0,0.0,1.0,0.216867,0.218631,0.216867,0.216867,69350400.0
1982-05-31,14.00,14.1200,14.00,14.00,85700.0,0.0,1.0,0.205839,0.207604,0.205839,0.205839,4799200.0
1982-06-30,12.75,12.8700,12.75,12.75,301900.0,0.0,1.0,0.187461,0.189225,0.187461,0.187461,16906400.0
1982-07-31,13.50,13.6200,13.50,13.50,172400.0,0.0,1.0,0.198488,0.200252,0.198488,0.198488,9654400.0
1982-08-31,18.00,18.1200,18.00,18.00,627500.0,0.0,1.0,0.264651,0.266415,0.264651,0.264651,35140000.0
1982-09-30,18.37,18.3700,18.25,18.25,333400.0,0.0,1.0,0.270091,0.270091,0.268326,0.268326,18670400.0
1982-10-31,25.12,25.3700,24.75,25.37,527300.0,0.0,1.0,0.369335,0.373010,0.363895,0.373010,29528800.0
1982-11-30,28.87,32.0000,28.75,31.88,710700.0,0.0,1.0,0.424470,0.470490,0.422706,0.468726,39799200.0
1982-12-31,30.00,30.3700,29.87,29.87,221700.0,0.0,1.0,0.441084,0.446524,0.439173,0.439173,12415200.0
1983-01-31,41.00,41.6200,40.13,40.87,839300.0,0.0,1.0,0.602815,0.611931,0.590024,0.600904,47000800.0
1983-02-28,46.75,46.8700,45.50,45.62,590600.0,0.0,1.0,0.687357,0.689121,0.668978,0.670742,33073600.0
1983-03-31,44.25,44.5000,42.25,42.25,380100.0,0.0,1.0,0.650600,0.654275,0.621194,0.621194,21285600.0
1983-04-30,50.00,50.7500,49.38,50.50,1376400.0,0.0,1.0,0.735141,0.746168,0.726025,0.742492,77078400.0
1983-05-31,59.25,59.2500,56.62,57.75,203300.0,0.0,1.0,0.871142,0.871142,0.832473,0.849088,11384800.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2015-10-31,120.99,121.2200,119.45,119.50,49365254.0,0.0,1.0,116.393793,116.615056,114.912295,114.960396,49365254.0
2015-11-30,117.99,119.4100,117.75,118.30,39180322.0,0.0,1.0,113.995883,115.367814,113.764007,114.295389,39180322.0
2015-12-31,107.01,107.0300,104.82,105.26,40912316.0,0.0,1.0,103.387570,103.406893,101.271705,101.696810,40912316.0
2016-01-31,94.79,97.3400,94.35,97.34,64416504.0,0.0,1.0,91.581233,94.044912,91.156128,94.044912,64416504.0
2016-02-29,96.86,98.2300,96.65,96.69,35216277.0,0.0,1.0,94.084911,95.415659,93.880927,93.919781,35216277.0
2016-03-31,109.72,109.9000,108.88,108.99,25888449.0,0.0,1.0,106.576465,106.751308,105.760531,105.867380,25888449.0
2016-04-30,93.99,94.7200,92.51,93.74,68531478.0,0.0,1.0,91.297138,92.006223,89.859540,91.054300,68531478.0
2016-05-31,99.60,100.4000,98.82,99.86,42307212.0,0.0,1.0,97.337844,98.119674,96.575559,97.591939,42307212.0
2016-06-30,94.44,95.7700,94.30,95.60,35836356.0,0.0,1.0,92.295040,93.594832,92.158220,93.428693,35836356.0
2016-07-31,104.19,104.5500,103.68,104.21,27733688.0,0.0,1.0,101.823594,102.175417,101.325177,101.843140,27733688.0
2016-08-31,105.66,106.5699,105.64,106.10,29662406.0,0.0,1.0,103.816156,104.710177,103.796505,104.248477,29662406.0
2016-09-30,112.46,113.3700,111.80,113.05,36379106.0,0.0,1.0,110.497491,111.391610,109.849008,111.077195,36379106.0
2016-10-31,113.65,114.2300,113.20,113.54,26419398.0,0.0,1.0,111.666724,112.236603,111.224577,111.558644,26419398.0
2016-11-30,111.56,112.2000,110.27,110.52,36162258.0,0.0,1.0,110.182071,110.814166,108.908004,109.154917,36162258.0
2016-12-31,116.65,117.2000,115.43,115.82,30586265.0,0.0,1.0,115.209202,115.752409,114.004271,114.389454,30586265.0
2017-01-31,121.15,121.3900,120.62,121.35,49200993.0,0.0,1.0,119.653620,119.890656,119.130167,119.851150,49200993.0
2017-02-28,137.08,137.4350,136.70,136.99,23482860.0,0.0,1.0,135.969633,136.321757,135.592711,135.880362,23482860.0
2017-03-31,143.72,144.2700,143.01,143.66,19661651.0,0.0,1.0,142.555848,143.101393,141.851599,142.496334,19661651.0
2017-04-30,144.09,144.3000,143.27,143.65,20247187.0,0.0,1.0,142.922851,143.131150,142.109493,142.486415,20247187.0
2017-05-31,153.97,154.1700,152.38,152.76,23162873.0,0.0,1.0,153.347799,153.546991,151.764225,152.142689,23162873.0
2017-06-30,144.45,144.9600,143.78,144.02,22328979.0,0.0,1.0,143.866270,144.374209,143.198978,143.438008,22328979.0
2017-07-31,149.90,150.3300,148.13,148.85,19422655.0,0.0,1.0,149.294246,149.722509,147.531399,148.248489,19422655.0
2017-08-31,163.64,164.5200,163.48,164.00,26412439.0,0.0,1.0,163.640000,164.520000,163.480000,164.000000,26412439.0
2017-09-30,153.21,154.1300,152.00,154.12,25856530.0,0.0,1.0,153.210000,154.130000,152.000000,154.120000,25856530.0
2017-10-31,167.90,169.6499,166.94,169.04,35474672.0,0.0,1.0,167.900000,169.649900,166.940000,169.040000,35474672.0
2017-11-30,170.43,172.1400,168.44,171.85,40172368.0,0.0,1.0,170.430000,172.140000,168.440000,171.850000,40172368.0
2017-12-31,170.52,170.5900,169.22,169.23,25643711.0,0.0,1.0,170.520000,170.590000,169.220000,169.230000,25643711.0
2018-01-31,166.87,168.4417,166.50,167.43,30984099.0,0.0,1.0,166.870000,168.441700,166.500000,167.430000,30984099.0
2018-02-28,179.26,180.6150,178.05,178.12,33604574.0,0.0,1.0,179.260000,180.615000,178.050000,178.120000,33604574.0
2018-03-31,173.68,175.1500,166.92,168.34,38962839.0,0.0,1.0,173.680000,175.150000,166.920000,168.340000,38962839.0

In [80]:
gg = []
ggN = []
for hh in IBMdata["Date"]:
    
    gg.append(f"{hh.year}-{hh.month}-{hh.day}")
    ggN.append(f"{hh.year}-{hh.month}-{hh.day}")
#     print(hh.month)
# gg.remove(-1)
len(gg)
del gg[-1]
len(ggN)

675

In [81]:
Volume = []
for Vo in IBMdata["Volume"]:
    Volume.append(Vo)
len(Volume)    
Close = []
for Co in IBMdata["Close"]:
    Close.append(Co)
len(Close)

675

In [82]:
year = 1962

x = 0
changes = []
while x < (len(IBMdata)-1):
    openV = IBMdata["Open"][x]

    closeV = IBMdata["Close"][x+1]
    changes.append(round((closeV-openV)/openV*100,2))

    x += 1
print(len(changes))

674

In [9]:
months = ["January","Febuary","March","April","May","June","July","August","Septemeber","October","November","December"]
year = 1962
labels = []
while year < 2018:
    for month in months:
        labels.append(str(month) + " " + str(year))
    year += 1    
labels.append("January 2018")
labels.append("Febuary 2018")
labels.append("March 2018")
labels.append("April 2018")
labels.append("May 2018")
labels.append("June 2018")
labels.append("July 2018")
labels.append("August 2018")


labels

['January 1962',
 'Febuary 1962',
 'March 1962',
 'April 1962',
 'May 1962',
 'June 1962',
 'July 1962',
 'August 1962',
 'Septemeber 1962',
 'October 1962',
 'November 1962',
 'December 1962',
 'January 1963',
 'Febuary 1963',
 'March 1963',
 'April 1963',
 'May 1963',
 'June 1963',
 'July 1963',
 'August 1963',
 'Septemeber 1963',
 'October 1963',
 'November 1963',
 'December 1963',
 'January 1964',
 'Febuary 1964',
 'March 1964',
 'April 1964',
 'May 1964',
 'June 1964',
 'July 1964',
 'August 1964',
 'Septemeber 1964',
 'October 1964',
 'November 1964',
 'December 1964',
 'January 1965',
 'Febuary 1965',
 'March 1965',
 'April 1965',
 'May 1965',
 'June 1965',
 'July 1965',
 'August 1965',
 'Septemeber 1965',
 'October 1965',
 'November 1965',
 'December 1965',
 'January 1966',
 'Febuary 1966',
 'March 1966',
 'April 1966',
 'May 1966',
 'June 1966',
 'July 1966',
 'August 1966',
 'Septemeber 1966',
 'October 1966',
 'November 1966',
 'December 1966',
 'January 1967',
 'Febuary 1967',
 'March 1967',
 'April 1967',
 'May 1967',
 'June 1967',
 'July 1967',
 'August 1967',
 'Septemeber 1967',
 'October 1967',
 'November 1967',
 'December 1967',
 'January 1968',
 'Febuary 1968',
 'March 1968',
 'April 1968',
 'May 1968',
 'June 1968',
 'July 1968',
 'August 1968',
 'Septemeber 1968',
 'October 1968',
 'November 1968',
 'December 1968',
 'January 1969',
 'Febuary 1969',
 'March 1969',
 'April 1969',
 'May 1969',
 'June 1969',
 'July 1969',
 'August 1969',
 'Septemeber 1969',
 'October 1969',
 'November 1969',
 'December 1969',
 'January 1970',
 'Febuary 1970',
 'March 1970',
 'April 1970',
 'May 1970',
 'June 1970',
 'July 1970',
 'August 1970',
 'Septemeber 1970',
 'October 1970',
 'November 1970',
 'December 1970',
 'January 1971',
 'Febuary 1971',
 'March 1971',
 'April 1971',
 'May 1971',
 'June 1971',
 'July 1971',
 'August 1971',
 'Septemeber 1971',
 'October 1971',
 'November 1971',
 'December 1971',
 'January 1972',
 'Febuary 1972',
 'March 1972',
 'April 1972',
 'May 1972',
 'June 1972',
 'July 1972',
 'August 1972',
 'Septemeber 1972',
 'October 1972',
 'November 1972',
 'December 1972',
 'January 1973',
 'Febuary 1973',
 'March 1973',
 'April 1973',
 'May 1973',
 'June 1973',
 'July 1973',
 'August 1973',
 'Septemeber 1973',
 'October 1973',
 'November 1973',
 'December 1973',
 'January 1974',
 'Febuary 1974',
 'March 1974',
 'April 1974',
 'May 1974',
 'June 1974',
 'July 1974',
 'August 1974',
 'Septemeber 1974',
 'October 1974',
 'November 1974',
 'December 1974',
 'January 1975',
 'Febuary 1975',
 'March 1975',
 'April 1975',
 'May 1975',
 'June 1975',
 'July 1975',
 'August 1975',
 'Septemeber 1975',
 'October 1975',
 'November 1975',
 'December 1975',
 'January 1976',
 'Febuary 1976',
 'March 1976',
 'April 1976',
 'May 1976',
 'June 1976',
 'July 1976',
 'August 1976',
 'Septemeber 1976',
 'October 1976',
 'November 1976',
 'December 1976',
 'January 1977',
 'Febuary 1977',
 'March 1977',
 'April 1977',
 'May 1977',
 'June 1977',
 'July 1977',
 'August 1977',
 'Septemeber 1977',
 'October 1977',
 'November 1977',
 'December 1977',
 'January 1978',
 'Febuary 1978',
 'March 1978',
 'April 1978',
 'May 1978',
 'June 1978',
 'July 1978',
 'August 1978',
 'Septemeber 1978',
 'October 1978',
 'November 1978',
 'December 1978',
 'January 1979',
 'Febuary 1979',
 'March 1979',
 'April 1979',
 'May 1979',
 'June 1979',
 'July 1979',
 'August 1979',
 'Septemeber 1979',
 'October 1979',
 'November 1979',
 'December 1979',
 'January 1980',
 'Febuary 1980',
 'March 1980',
 'April 1980',
 'May 1980',
 'June 1980',
 'July 1980',
 'August 1980',
 'Septemeber 1980',
 'October 1980',
 'November 1980',
 'December 1980',
 'January 1981',
 'Febuary 1981',
 'March 1981',
 'April 1981',
 'May 1981',
 'June 1981',
 'July 1981',
 'August 1981',
 'Septemeber 1981',
 'October 1981',
 'November 1981',
 'December 1981',
 'January 1982',
 'Febuary 1982',
 'March 1982',
 'April 1982',
 'May 1982',
 'June 1982',
 'July 1982',
 'August 1982',
 'Septemeber 1982',
 'October 1982',
 'November 1982',
 'December 1982',
 'January 1983',
 'Febuary 1983',
 'March 1983',
 'April 1983',
 'May 1983',
 'June 1983',
 'July 1983',
 'August 1983',
 'Septemeber 1983',
 'October 1983',
 'November 1983',
 'December 1983',
 'January 1984',
 'Febuary 1984',
 'March 1984',
 'April 1984',
 'May 1984',
 'June 1984',
 'July 1984',
 'August 1984',
 'Septemeber 1984',
 'October 1984',
 'November 1984',
 'December 1984',
 'January 1985',
 'Febuary 1985',
 'March 1985',
 'April 1985',
 'May 1985',
 'June 1985',
 'July 1985',
 'August 1985',
 'Septemeber 1985',
 'October 1985',
 'November 1985',
 'December 1985',
 'January 1986',
 'Febuary 1986',
 'March 1986',
 'April 1986',
 'May 1986',
 'June 1986',
 'July 1986',
 'August 1986',
 'Septemeber 1986',
 'October 1986',
 'November 1986',
 'December 1986',
 'January 1987',
 'Febuary 1987',
 'March 1987',
 'April 1987',
 'May 1987',
 'June 1987',
 'July 1987',
 'August 1987',
 'Septemeber 1987',
 'October 1987',
 'November 1987',
 'December 1987',
 'January 1988',
 'Febuary 1988',
 'March 1988',
 'April 1988',
 'May 1988',
 'June 1988',
 'July 1988',
 'August 1988',
 'Septemeber 1988',
 'October 1988',
 'November 1988',
 'December 1988',
 'January 1989',
 'Febuary 1989',
 'March 1989',
 'April 1989',
 'May 1989',
 'June 1989',
 'July 1989',
 'August 1989',
 'Septemeber 1989',
 'October 1989',
 'November 1989',
 'December 1989',
 'January 1990',
 'Febuary 1990',
 'March 1990',
 'April 1990',
 'May 1990',
 'June 1990',
 'July 1990',
 'August 1990',
 'Septemeber 1990',
 'October 1990',
 'November 1990',
 'December 1990',
 'January 1991',
 'Febuary 1991',
 'March 1991',
 'April 1991',
 'May 1991',
 'June 1991',
 'July 1991',
 'August 1991',
 'Septemeber 1991',
 'October 1991',
 'November 1991',
 'December 1991',
 'January 1992',
 'Febuary 1992',
 'March 1992',
 'April 1992',
 'May 1992',
 'June 1992',
 'July 1992',
 'August 1992',
 'Septemeber 1992',
 'October 1992',
 'November 1992',
 'December 1992',
 'January 1993',
 'Febuary 1993',
 'March 1993',
 'April 1993',
 'May 1993',
 'June 1993',
 'July 1993',
 'August 1993',
 'Septemeber 1993',
 'October 1993',
 'November 1993',
 'December 1993',
 'January 1994',
 'Febuary 1994',
 'March 1994',
 'April 1994',
 'May 1994',
 'June 1994',
 'July 1994',
 'August 1994',
 'Septemeber 1994',
 'October 1994',
 'November 1994',
 'December 1994',
 'January 1995',
 'Febuary 1995',
 'March 1995',
 'April 1995',
 'May 1995',
 'June 1995',
 'July 1995',
 'August 1995',
 'Septemeber 1995',
 'October 1995',
 'November 1995',
 'December 1995',
 'January 1996',
 'Febuary 1996',
 'March 1996',
 'April 1996',
 'May 1996',
 'June 1996',
 'July 1996',
 'August 1996',
 'Septemeber 1996',
 'October 1996',
 'November 1996',
 'December 1996',
 'January 1997',
 'Febuary 1997',
 'March 1997',
 'April 1997',
 'May 1997',
 'June 1997',
 'July 1997',
 'August 1997',
 'Septemeber 1997',
 'October 1997',
 'November 1997',
 'December 1997',
 'January 1998',
 'Febuary 1998',
 'March 1998',
 'April 1998',
 'May 1998',
 'June 1998',
 'July 1998',
 'August 1998',
 'Septemeber 1998',
 'October 1998',
 'November 1998',
 'December 1998',
 'January 1999',
 'Febuary 1999',
 'March 1999',
 'April 1999',
 'May 1999',
 'June 1999',
 'July 1999',
 'August 1999',
 'Septemeber 1999',
 'October 1999',
 'November 1999',
 'December 1999',
 'January 2000',
 'Febuary 2000',
 'March 2000',
 'April 2000',
 'May 2000',
 'June 2000',
 'July 2000',
 'August 2000',
 'Septemeber 2000',
 'October 2000',
 'November 2000',
 'December 2000',
 'January 2001',
 'Febuary 2001',
 'March 2001',
 'April 2001',
 'May 2001',
 'June 2001',
 'July 2001',
 'August 2001',
 'Septemeber 2001',
 'October 2001',
 'November 2001',
 'December 2001',
 'January 2002',
 'Febuary 2002',
 'March 2002',
 'April 2002',
 'May 2002',
 'June 2002',
 'July 2002',
 'August 2002',
 'Septemeber 2002',
 'October 2002',
 'November 2002',
 'December 2002',
 'January 2003',
 'Febuary 2003',
 'March 2003',
 'April 2003',
 'May 2003',
 'June 2003',
 'July 2003',
 'August 2003',
 'Septemeber 2003',
 'October 2003',
 'November 2003',
 'December 2003',
 'January 2004',
 'Febuary 2004',
 'March 2004',
 'April 2004',
 'May 2004',
 'June 2004',
 'July 2004',
 'August 2004',
 'Septemeber 2004',
 'October 2004',
 'November 2004',
 'December 2004',
 'January 2005',
 'Febuary 2005',
 'March 2005',
 'April 2005',
 'May 2005',
 'June 2005',
 'July 2005',
 'August 2005',
 'Septemeber 2005',
 'October 2005',
 'November 2005',
 'December 2005',
 'January 2006',
 'Febuary 2006',
 'March 2006',
 'April 2006',
 'May 2006',
 'June 2006',
 'July 2006',
 'August 2006',
 'Septemeber 2006',
 'October 2006',
 'November 2006',
 'December 2006',
 'January 2007',
 'Febuary 2007',
 'March 2007',
 'April 2007',
 'May 2007',
 'June 2007',
 'July 2007',
 'August 2007',
 'Septemeber 2007',
 'October 2007',
 'November 2007',
 'December 2007',
 'January 2008',
 'Febuary 2008',
 'March 2008',
 'April 2008',
 'May 2008',
 'June 2008',
 'July 2008',
 'August 2008',
 'Septemeber 2008',
 'October 2008',
 'November 2008',
 'December 2008',
 'January 2009',
 'Febuary 2009',
 'March 2009',
 'April 2009',
 'May 2009',
 'June 2009',
 'July 2009',
 'August 2009',
 'Septemeber 2009',
 'October 2009',
 'November 2009',
 'December 2009',
 'January 2010',
 'Febuary 2010',
 'March 2010',
 'April 2010',
 'May 2010',
 'June 2010',
 'July 2010',
 'August 2010',
 'Septemeber 2010',
 'October 2010',
 'November 2010',
 'December 2010',
 'January 2011',
 'Febuary 2011',
 'March 2011',
 'April 2011',
 'May 2011',
 'June 2011',
 'July 2011',
 'August 2011',
 'Septemeber 2011',
 'October 2011',
 'November 2011',
 'December 2011',
 'January 2012',
 'Febuary 2012',
 'March 2012',
 'April 2012',
 'May 2012',
 'June 2012',
 'July 2012',
 'August 2012',
 'Septemeber 2012',
 'October 2012',
 'November 2012',
 'December 2012',
 'January 2013',
 'Febuary 2013',
 'March 2013',
 'April 2013',
 'May 2013',
 'June 2013',
 'July 2013',
 'August 2013',
 'Septemeber 2013',
 'October 2013',
 'November 2013',
 'December 2013',
 'January 2014',
 'Febuary 2014',
 'March 2014',
 'April 2014',
 'May 2014',
 'June 2014',
 'July 2014',
 'August 2014',
 'Septemeber 2014',
 'October 2014',
 'November 2014',
 'December 2014',
 'January 2015',
 'Febuary 2015',
 'March 2015',
 'April 2015',
 'May 2015',
 'June 2015',
 'July 2015',
 'August 2015',
 'Septemeber 2015',
 'October 2015',
 'November 2015',
 'December 2015',
 'January 2016',
 'Febuary 2016',
 'March 2016',
 'April 2016',
 'May 2016',
 'June 2016',
 'July 2016',
 'August 2016',
 'Septemeber 2016',
 'October 2016',
 'November 2016',
 'December 2016',
 'January 2017',
 'Febuary 2017',
 'March 2017',
 'April 2017',
 'May 2017',
 'June 2017',
 'July 2017',
 'August 2017',
 'Septemeber 2017',
 'October 2017',
 'November 2017',
 'December 2017',
 'January 2018',
 'Febuary 2018',
 'March 2018',
 'April 2018',
 'May 2018',
 'June 2018',
 'July 2018',
 'August 2018']

In [84]:
IBM_json = {
    "numbers": changes, 
    "labels": labels,
    "Dates": gg,
    "Dates_Normal": ggN,
    "Volume": Volume, 
    "Close": Close
}

NameError: name 'labels' is not defined

In [11]:
import pymongo

# Create connection variable
conn = 'mongodb://localhost:27017'

# Pass connection to the pymongo instance.
client = pymongo.MongoClient(conn)

# Connect to a database. Will create one if not already available.
db = client.IBM_y_y

# Drops collection if available to remove duplicates
db.ibm_y_o_y.drop()

# Creates a collection in the database and insert document
db.ibm_y_o_y.insert_one(
    IBM_json
)

In [40]:
681/4

170.25

In [43]:
ib1 = IBMdata.iloc[:170]
ib2 = IBMdata.iloc[170:340]
ib3 = IBMdata.iloc[340:510]
ib4 = IBMdata.iloc[510:]
print(len(ib1))
print(len(ib2))
print(len(ib3))
print(len(ib4))

170
170
170
171

In [58]:
ib1_O = ib1.iloc[:1]["Open"]
ib1_C = ib1.iloc[169:]["Close"]
ib1D = round((int(ib1_C)-int(ib1_O))/int(ib1_O)*100,2)

ib2_O = ib2.iloc[:1]["Open"]
ib2_C = ib2.iloc[169:]["Close"]
ib2D = round((int(ib2_C)-int(ib2_O))/int(ib2_O)*100,2)

ib3_O = ib3.iloc[:1]["Open"]
ib3_C = ib3.iloc[169:]["Close"]
ib3D = round((int(ib3_C)-int(ib3_O))/int(ib3_O)*100,2)

ib4_O = ib4.iloc[:1]["Open"]
ib4_C = ib4.iloc[170:]["Close"]
ib4D = round((int(ib4_C)-int(ib4_O))/int(ib4_O)*100,2)

In [59]:
ib4D

72.09